//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio2.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IGuardarFormEstudiante")]
    public interface IGuardarFormEstudiante {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuardarFormEstudiante/receiveDataForm", ReplyAction="http://tempuri.org/IGuardarFormEstudiante/receiveDataFormResponse")]
        void receiveDataForm(string nombre, string apellido, string correo, string sexo, string direccion, string ciudad, string requerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuardarFormEstudiante/receiveDataForm", ReplyAction="http://tempuri.org/IGuardarFormEstudiante/receiveDataFormResponse")]
        System.Threading.Tasks.Task receiveDataFormAsync(string nombre, string apellido, string correo, string sexo, string direccion, string ciudad, string requerimiento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGuardarFormEstudianteChannel : Laboratorio2.ServiceReference3.IGuardarFormEstudiante, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuardarFormEstudianteClient : System.ServiceModel.ClientBase<Laboratorio2.ServiceReference3.IGuardarFormEstudiante>, Laboratorio2.ServiceReference3.IGuardarFormEstudiante {
        
        public GuardarFormEstudianteClient() {
        }
        
        public GuardarFormEstudianteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GuardarFormEstudianteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuardarFormEstudianteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuardarFormEstudianteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void receiveDataForm(string nombre, string apellido, string correo, string sexo, string direccion, string ciudad, string requerimiento) {
            base.Channel.receiveDataForm(nombre, apellido, correo, sexo, direccion, ciudad, requerimiento);
        }
        
        public System.Threading.Tasks.Task receiveDataFormAsync(string nombre, string apellido, string correo, string sexo, string direccion, string ciudad, string requerimiento) {
            return base.Channel.receiveDataFormAsync(nombre, apellido, correo, sexo, direccion, ciudad, requerimiento);
        }
    }
}
